# Generated by Django 5.2.1 on 2025-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('owner', 'Salon Owner'), ('staff', 'Staff')], default='client', max_length=20),
        ),
    ]
