# Generated by Django 5.2.1 on 2025-08-05 06:26

import django.db.models.deletion
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_initial'),
        ('userauths', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon_image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
