# Generated by Django 5.2 on 2025-05-02 18:45

import datetime
import django.core.validators
import salon.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Unisex', 'Unisex')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['booking_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=salon.models.salon_image_upload_path)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('In Review', 'In Review'), ('Live', 'Live')], default='In Review', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('salon_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalonFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Salon FAQs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalonFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(blank=True, choices=[('Bootstrap Icons', 'Bootstrap Icons'), ('Fontawesome Icons', 'Fontawesome Icons'), ('Box Icons', 'Box Icons'), ('Remi Icons', 'Remi Icons'), ('Flat Icons', 'Flat Icons')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Salon Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=salon.models.salon_image_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Salon Gallery',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalonServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('women_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('men_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('children_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.CharField(choices=[('Hair', 'Hair'), ('Nails', 'Nails'), ('Skincare', 'Skincare'), ('Waxing', 'Waxing'), ('Makeup', 'Makeup'), ('Massage', 'Massage'), ('Specialty', 'Specialty')], max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Unisex', 'Unisex')], default='Unisex', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Font icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Service',
                'verbose_name_plural': 'Salon Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffOnDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Hair Stylist', 'Hair Stylist'), ('Nail Technician', 'Nail Technician'), ('Esthetician', 'Esthetician'), ('Barber', 'Barber'), ('Makeup Artist', 'Makeup Artist'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('break_start', models.TimeField(default=datetime.time(13, 0))),
                ('break_duration', models.PositiveIntegerField(default=60)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff On Duty',
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
    ]
