# Generated by Django 5.2.4 on 2025-07-14 17:31

import datetime
import django.core.validators
import django.db.models.deletion
import salon.models
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=salon.models.salon_image_upload_path)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('In Review', 'In Review'), ('Live', 'Live')], default='In Review', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('salon_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalonAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fa-wifi')", max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon amenities',
            },
        ),
        migrations.CreateModel(
            name='SalonFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon FAQs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=salon.models.gallery_image_upload_path)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon Gallery',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalonNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='salon.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon Notification',
                'verbose_name_plural': 'Salon Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_parking', models.BooleanField(default=True)),
                ('parking_details', models.TextField(blank=True)),
                ('valet_available', models.BooleanField(default=False)),
                ('valet_days', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='salon.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='salon.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon Review',
                'verbose_name_plural': 'Salon Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('women_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('men_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('children_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.CharField(choices=[('Hair', 'Hair'), ('Nails', 'Nails'), ('Skincare', 'Skincare'), ('Waxing', 'Waxing'), ('Makeup', 'Makeup'), ('Massage', 'Massage'), ('Specialty', 'Specialty')], max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Unisex', 'Unisex')], default='Unisex', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.salon')),
            ],
            options={
                'verbose_name': 'Salon Service',
                'verbose_name_plural': 'Salon Services',
                'ordering': ['category', 'name'],
                'unique_together': {('salon', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_friday', models.CharField(default='9AM - 8PM', max_length=100)),
                ('saturday', models.CharField(default='9AM - 6PM', max_length=100)),
                ('sunday', models.CharField(default='10AM - 4PM', max_length=100)),
                ('holidays', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salon.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(blank=True, choices=[('Bootstrap Icons', 'Bootstrap Icons'), ('Fontawesome Icons', 'Fontawesome Icons'), ('Box Icons', 'Box Icons'), ('Remi Icons', 'Remi Icons'), ('Flat Icons', 'Flat Icons')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon Features',
                'ordering': ['name'],
                'unique_together': {('salon', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffOnDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Hair Stylist', 'Hair Stylist'), ('Nail Technician', 'Nail Technician'), ('Esthetician', 'Esthetician'), ('Barber', 'Barber'), ('Makeup Artist', 'Makeup Artist'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('break_start', models.TimeField(default=datetime.time(13, 0))),
                ('break_duration', models.PositiveIntegerField(default=60)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end', models.TimeField(default=datetime.time(17, 0))),
                ('friday_start', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon.salon')),
                ('specialization', models.ManyToManyField(blank=True, related_name='qualified_staff', to='salon.salonservices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff On Duty',
                'ordering': ['display_order', 'user__first_name'],
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
