# Generated by Django 5.2.4 on 2025-07-12 00:50

import datetime
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='salon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonamenity',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfaq',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfeatures',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salongallery',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonnotification',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonparking',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonpaymentoption',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.salonservices'),
        ),
        migrations.AddField(
            model_name='salonworkinghours',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='qualified_staff', to='salon.salonservices'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salonfeatures',
            unique_together={('salon', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salonservices',
            unique_together={('salon', 'name')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='salon_booki_booking_fae6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='salon_booki_user_id_89d2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff_member', 'booking_date'], name='salon_booki_staff_m_2f5d9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('salon', 'booking_date', 'start_time', 'staff_member'), name='unique_staff_booking'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 7, 12))), name='booking_date_cannot_be_in_past'),
        ),
        migrations.AlterUniqueTogether(
            name='staffonduty',
            unique_together={('user', 'salon')},
        ),
    ]
