# Generated by Django 5.2 on 2025-05-02 19:24

import salon.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_initial'),
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='salongallery',
            name='image',
            field=models.ImageField(upload_to=salon.models.gallery_image_upload_path),
        ),
    ]
