# Generated by Django 5.2.4 on 2025-07-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonamenity',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfaq',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfeatures',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salongallery',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonnotification',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonparking',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonpaymentoption',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonworkinghours',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salon.salon'),
        ),
        migrations.AlterUniqueTogether(
            name='salonfeatures',
            unique_together={('salon', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salonservices',
            unique_together={('salon', 'name')},
        ),
    ]
