# Generated by Django 5.2.1 on 2025-07-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_booking_booking_date_cannot_be_in_past_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonservices',
            name='icon',
        ),
    ]
