# Generated by Django 5.2 on 2025-05-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_salonfeatures_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fa-wifi')", max_length=50)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon amenities',
            },
        ),
        migrations.CreateModel(
            name='SalonParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_parking', models.BooleanField(default=True)),
                ('parking_details', models.TextField(blank=True)),
                ('valet_available', models.BooleanField(default=False)),
                ('valet_days', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='salon.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='salon.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_friday', models.CharField(default='9AM - 8PM', max_length=100)),
                ('saturday', models.CharField(default='9AM - 6PM', max_length=100)),
                ('sunday', models.CharField(default='10AM - 4PM', max_length=100)),
                ('holidays', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salon.salon')),
            ],
        ),
    ]
