# Generated by Django 5.2.1 on 2025-06-10 12:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_payment_alter_booking_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processed_by',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_cannot_be_in_past',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 6, 10))), name='booking_date_cannot_be_in_past'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
