# Generated by Django 5.2.1 on 2025-06-17 10:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_remove_payment_booking_remove_payment_processed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_cannot_be_in_past',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 6, 17))), name='booking_date_cannot_be_in_past'),
        ),
    ]
