# Generated by Django 5.2 on 2025-05-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfaq',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonfeatures',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salongallery',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.salonservices'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon.salon'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='qualified_staff', to='salon.salonservices'),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salonservices',
            unique_together={('salon', 'name')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='salon_booki_booking_fae6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='salon_booki_user_id_89d2c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('salon', 'booking_date', 'start_time', 'staff_member')},
        ),
        migrations.AlterUniqueTogether(
            name='staffonduty',
            unique_together={('user', 'salon')},
        ),
    ]
