# Generated by Django 5.2 on 2025-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_salonamenity_salonparking_salonpaymentoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonamenity',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
