# Generated by Django 5.2 on 2025-05-17 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_salonamenity_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffonduty',
            name='friday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='staffonduty',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
