# Generated by Django 5.2.4 on 2025-07-16 12:53

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOnDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Hair Stylist', 'Hair Stylist'), ('Nail Technician', 'Nail Technician'), ('Esthetician', 'Esthetician'), ('Barber', 'Barber'), ('Makeup Artist', 'Makeup Artist'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('break_start', models.TimeField(default=datetime.time(13, 0))),
                ('break_duration', models.PositiveIntegerField(default=60)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end', models.TimeField(default=datetime.time(17, 0))),
                ('friday_start', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon.salon')),
                ('specialization', models.ManyToManyField(blank=True, related_name='qualified_staff', to='salon.salonservices')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff On Duty',
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
    ]
