# Generated by Django 5.2.4 on 2025-07-16 12:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='booking_boo_booking_b98d74_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_boo_user_id_dddf68_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff_member', 'booking_date'], name='booking_boo_staff_m_a3d28a_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('salon', 'booking_date', 'start_time', 'staff_member'), name='unique_staff_booking'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 7, 16))), name='booking_date_cannot_be_in_past'),
        ),
    ]
