# Generated by Django 5.2.4 on 2025-07-17 20:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_staff'),
        ('salon', '0003_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_cannot_be_in_past',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ip_address',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 7, 17))), name='booking_date_cannot_be_in_past'),
        ),
    ]
