# Generated by Django 5.2.1 on 2025-08-05 06:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_booking_date_cannot_be_in_past_and_more'),
        ('salon', '0003_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_cannot_be_in_past',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2025, 8, 5))), name='booking_date_cannot_be_in_past'),
        ),
    ]
